let startCalculationBtn = document.getElementById('start'),
    resultValue = document.querySelectorAll('div .result-table > div[class$="-value"]'),
    expensesInput = document.querySelectorAll('input[class="expenses-item"]'),
    btns = document.getElementsByTagName('button'),
    approveExpense = btns[0],
    approveOptionalExpenses = btns[1],
    calculate = btns[2],
    optionalExpenses = document.querySelectorAll('input[class="optionalexpenses-item"]'),
    income = document.querySelector('input[class="optionalExpenses"]'),
    savings = document.querySelector('#savings'),
    sum = document.querySelector('input[class="choose-sum"]'),
    percent = document.querySelector('input[class="choose-percent"]'),
    year = document.querySelector('input[class="year-value"]'),
    month = document.querySelector('input[class="month-value"]'),
    day = document.querySelector('input[class="day-value"]');
